---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support, cloud manager 
summary: 'Astra Trident est un projet open source entièrement pris en charge et géré par NetApp. Astra Trident s"intègre de manière native avec Kubernetes et son framework de volumes persistants pour provisionner et gérer les volumes de manière transparente à partir des systèmes qui exécutent toutes les combinaisons de plateformes de stockage NetApp.' 
---
= Gestion des données Kubernetes dans BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident est un projet open source entièrement pris en charge et géré par NetApp. Astra Trident s'intègre de manière native avec Kubernetes et son framework de volumes persistants pour provisionner et gérer les volumes de manière transparente à partir des systèmes qui exécutent toutes les combinaisons de plateformes de stockage NetApp. link:https://docs.netapp.com/us-en/trident/index.html["En savoir plus sur Trident"^].



== Caractéristiques

À l'aide d'un link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html["BlueXP"^] (Anciennement Cloud Manager) et une version compatible d'Astra Trident déployée à l'aide de l'opérateur Trident, vous pouvez :

* Ajoutez et gérez des clusters Kubernetes
* link:./task/task-k8s-manage-trident.html["Installez, mettez à niveau ou désinstallez Astra Trident"]
* link:./task/task-k8s-manage-storage-classes.html["Ajouter et supprimer des classes de stockage"]
* link:./task/task-k8s-manage-persistent-volumes.html["Afficher les volumes persistants"]
* link:./task/task-k8s-manage-remove-cluster.html["Supprimez les clusters Kubernetes"] depuis l'espace de travail
* link:./task/task-kubernetes-enable-services.html["Activez ou affichez Cloud Backup"]




== Déploiements Kubernetes pris en charge

BlueXP prend en charge les clusters Kubernetes gérés dans :

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service (Amazon EKS)"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service (AKS)"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine (GKE)"]




== Prise en charge des déploiements Astra Trident

L'une des quatre versions les plus récentes d'Astra Trident link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Déployé à l'aide de l'opérateur Trident"^] est obligatoire.


NOTE: Astra Trident déployé avec `tridentctl` n'est pas pris en charge. Si vous avez déployé Astra Trident avec `tridentctl`, Vous ne pouvez pas utiliser BlueXP pour gérer vos clusters Kubernetes. Vous devez  et réinstaller link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Utilisation de l'opérateur Trident"^] ou link:./task/task-k8s-manage-trident.html["Utilisation de BlueXP"].

Vous pouvez installer ou mettre à niveau la dernière version d'Astra Trident directement à partir de BlueXP.

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["Lisez les conditions préalables à l'Astra Trident"^]



== Stockage interne pris en charge

NetApp Astra Trident doit être installé sur chaque cluster Kubernetes, et Cloud Volumes ONTAP ou Amazon FSX pour ONTAP doit être configuré en tant que stockage back-end pour les clusters.



== Le coût

Ce n'est pas facturé pour _découvrir_ vos clusters Kubernetes dans BlueXP, mais vous serez facturé lorsque vous sauvegardez des volumes persistants à l'aide de Cloud Backup Service.
