---
settings:
  name: Kubernetes clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation sur les clusters Kubernetes
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: En savoir plus sur la gestion des données Kubernetes
      url: "/concept-kubernetes.html"
    - title: Démarrage rapide
      url: "/task/task-k8s-quick-start.html"
  - title: De formation
    entries:
    - title: Clusters Kubernetes sur AWS
      url: "/requirements/kubernetes-reqs-aws.html"
    - title: Clusters Kubernetes sur Azure
      url: "/requirements/kubernetes-reqs-aks.html"
    - title: Clusters Kubernetes sur Google Cloud
      url: "/requirements/kubernetes-reqs-gke.html"
    - title: Clusters Kubernetes sur OpenShift
      url: "/requirements/kubernetes-reqs-openshift.html"
  - title: Ajouter des clusters Kubernetes
    entries:
    - title: Ajoutez des clusters sur AWS
      url: "/task/task-kubernetes-discover-aws.html"
    - title: Ajout de clusters sur Azure
      url: "/task/task-kubernetes-discover-azure.html"
    - title: Ajoutez des clusters sur Google Cloud
      url: "/task/task-kubernetes-discover-gke.html"
    - title: Importez des clusters OpenShift
      url: "/task/task-kubernetes-discover-openshift.html"
  - title: Gérez les clusters Kubernetes
    entries:
    - title: Gérez Astra Trident
      url: "/task/task-k8s-manage-trident.html"
    - title: Gérer les classes de stockage
      url: "/task/task-k8s-manage-storage-classes.html"
    - title: Afficher les volumes persistants
      url: "/task/task-k8s-manage-persistent-volumes.html"
    - title: Supprimer les clusters
      url: "/task/task-k8s-manage-remove-cluster.html"
    - title: Activez les services de données cloud NetApp
      url: "/task/task-kubernetes-enable-services.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/support/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Toute la documentation BlueXP
